version: '3.8'

services:
  backend:
    image: delmat238/familybass-drive-backend:latest
    restart: unless-stopped
    environment:
      - PORT=8080
      - JWT_SECRET=4QLWdBcnsuKDlRUSlzrgYA+0Uf/5uvnxCkx/PdJrPWM=
      - ADMIN_EMAIL=matdelhomel@gmail.com
      - ADMIN_PASSWORD=password
      - DATA_DIR=/data
    ports:
      - "8080:8080"
    volumes:
      - drive-data:/data
  frontend:
    image: delmat238/familybass-drive-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  drive-data: